---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-client-svc
  labels:
    component: elasticsearch-client-svc
    role: client
spec:
  clusterIP: None
  selector:
    component: elasticsearch
    role: client
  ports:
    - name: http
      port: 9200
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch-client-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: es.fzymgc.house
      http:
        paths:
          - backend:
              serviceName: elasticsearch-client-svc
              servicePort: http
