apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-master
  labels:
    component: elasticsearch
    role: master
spec:
  clusterIP: None
  selector:
    component: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
